- README.rst
- dask_cloudprovider/cloudprovider.yaml
I've asked RTD to change the docs slug to `dask-cloudprovider`. Removing the docs link for now to avoid sending traffic to the old address.
> Remove old docs links

- dask_cloudprovider/cloudprovider.yaml
- requirements.txt
This library requires some changes that went into distributed 2.2.0. Bumping minimum versions here to be safe.
Closes #18
> Bump dask and distributed minimum versions to 2.2.0

- dask_cloudprovider/providers/aws/ecs.py
Fixes #28.
Looks like the command was being overridden and was being set back to `dask-worker`. Here we pass the number of gpus to the worker task so it can decide for itself.
> Pass GPU info to worker task

- dask_cloudprovider/providers/aws/ecs.py
Closes #33 
From run_task response documentation, there can only be `tasks` or `failures`. Checks for `tasks` if not raises an exception with the contents of the run_task response.
> add task error handling

- dask_cloudprovider/providers/aws/ecs.py
Current method of getting the task id assumes that the task ID is the second value in a split of the task_arn on /.
Our task ARN looks like this:
arn:aws:ecs:<REGION>:<ACCT_ID>:task/<CLUSTER_NAME>/<TASK_ID>
I cannot validate what the original was assumed to look like but getting the last value from the split should work for both as the task ID should be the last value in the list always.
> add get last possible value from task arn

- dask_cloudprovider/cloudprovider.yaml
- dask_cloudprovider/providers/aws/ecs.py
Fixes bug where you cannot set the task environment variables inside `cloudprovider.yaml`
> add get environment from config yaml

- dask_cloudprovider/providers/aws/ecs.py
- dask_cloudprovider/providers/aws/helper.py
- dask_cloudprovider/providers/aws/tests/test_helper.py
**Fixes**
https://github.com/dask/dask-cloudprovider/issues/34
**What**
Adds exponential backoff to get_log_events along with a warning message that this is happening. Max backoff is set at 5 seconds
Adapted from:
https://aws.amazon.com/blogs/messaging-and-targeting/how-to-handle-a-throttling-maximum-sending-rate-exceeded-error/
> adds exponential backoff to get_log_events

- dask_cloudprovider/providers/aws/ecs.py
When launching a FarGate cluster on a non-default VPC, the automatic Security Group Creation fails as shown below.
This occurs because the ingress rules are referencing the security group by GroupName, however to reference a security group in a non-default VPC you are required to use GroupId. See [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.authorize_security_group_ingress).
Easy fix, just need to reference the newly created SG by GroupId instead of GroupName.
```
~/SageMaker/myenvs/pangeo/lib/python3.6/site-packages/dask_cloudprovider/providers/aws/ecs.py in _start(self)
720             self._security_groups = (
721                 self.config.get("security_groups")
--> 722                 or await …
```
> Fix unable to create Security Group in non-default VPC

- dask_cloudprovider/providers/aws/ecs.py
Previously, a Fargate cluster would always use a public IP. For organizations with security and compliance constraints, they would need to use Fargate with a private subnet in a VPC that isn't reachable from the public Internet.
> Support avoiding use of a public IP with Fargate

- dask_cloudprovider/cloudprovider.yaml
- dask_cloudprovider/providers/aws/ecs.py
In order to support TLS encryption, we need to be able to pass command line arguments like `--tls-cert`, `--tls-key`, etc. to both dask-scheduler and dask-worker. This PR allows for arbitrary
additional command line arguments, so that any valid command line args to dask-scheduler and dask-worker are supported.
> Allow extra command line args to scheduler & worker

- dask_cloudprovider/cloudprovider.yaml
- dask_cloudprovider/providers/aws/ecs.py
Fargate allows for specifying the platformVersion with strings like "1.4.0" or "LATEST". Different platform versions have different capabilities, e.g. mounting EFS drives, etc. This PR allows users to specify a platform version string.
> Support specifying platformVersion for Fargate

- .circleci/config.yml
- dask_cloudprovider/providers/azure/azureml.py
This the PR for the first issue discussed in https://github.com/dask/dask-cloudprovider/issues/116
Now resource group name for VNET can be explicitly passed. If the resource group name for VNET is passed then that will be used while creating the VNET. If resource group name is not passed, but the names for VNET and SUBNET are passed, then resource group for the workspace will be used while creating the VNET.
Also added documentation for vnet, subnet, vnet_resource_group.
> Allowing explicit passing of the resource group for VNET

- dask_cloudprovider/providers/aws/ecs.py
- dask_cloudprovider/providers/azure/azureml.py
- dask_cloudprovider/utils/timeout.py
- doc/source/index.rst
I'm just starting to get familiar with this project and wanted to find some small ways to contribute, so I ran `aspell` over this repo tonight. That turned up a handful of small typos in comments and documentation. This PR proposes fixing them.
Thanks for you time and consideration.
> fix typos in documentation

- .readthedocs.yml
Closes #136 
Looks like docs have been broken since we made dependencies optional. This PR adds all optional depencies to the RTD build.
> Update RTD install config to include extra packages

- dask_cloudprovider/providers/aws/ecs.py
Fixes #56.
We currently poll for the pending container status every second until it is running. If ECS takes a long time to start we can eventually run into a `ThrottlingException`.
This PR catches the exception and continues retrying but with an exponential backoff to a maximum of 20 seconds. Once a request is successful it will resume polling every second until the exception is hit again.
This will continue indefinitely until the container moves to a running or failed state.
> Backoff and retry status polling

- dask_cloudprovider/providers/aws/ecs.py
This PR allows to specify extra parameters for the scheduler and workers ECS tasks.
For example, you can set placements constraints or strategy.
Initially motivation as in #147 - the change allows to ensure scheduler is placed to least powerful instance.
Example:
```python
scheduler_task_kwargs={
'placementConstraints': [{
'type': 'memberOf',
'expression': 'attribute:ecs.instance-type == t2.micro'
}]
}
with ECSCluster(scheduler_task_kwargs=scheduler_task_kwargs, ...) as cluster:
...
```
> Extra keyword arguments for ECS tasks

- dask_cloudprovider/aws/ecs.py
- doc/source/troubleshooting.rst
I've been using `dask-cloudprovider` a lot recently to test things and come up with reproducible examples.
Through this experience, I learned that ECS / Fargate only allow task definitions to choose from a finite list of CPU and memory settings. This is an AWS limitation and not a `dask-cloudprovider` one, but it took me a bit of investigation to figure that out.
> botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the RegisterTaskDefinition operation: No Fargate configuration exists for given values.
This PR proposes adding a link to the [valid config values for ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html) in the docs, so that when people search the `dask-cloudprovider` docs or Google for this error, …
> [docs] document valid config options for ECS / Fargate

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/aws/tests/test_ec2.py
- dask_cloudprovider/digitalocean/droplet.py
- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/gcp/tests/test_gcp.py
- dask_cloudprovider/generic/cloud-init.yaml.j2
- dask_cloudprovider/generic/vmcluster.py
Add env_vars kwarg to VM cluster managers.
For example
```python
>>> from dask_cloudprovider.aws import EC2Cluster
>>> cluster = EC2Cluster(env_vars={"FOO": "bar"})
```
would result in the Docker command being generated as
```
docker run --net=host -e FOO=bar daskdev/dask:latest dask-worker <scheduler ip>
```
and then once you have connected a client you should be able to access it
```python
>>> import os
>>> from dask.distributed import Client
>>> client = Client(cluster)
>>> client.submit(lambda: os.environ["FOO"])
'bar'
```
> Add env_vars kwarg to VM cluster managers

- dask_cloudprovider/gcp/instances.py
To use NVIDIA A100 GPUs on GCP you use either the `a2-highgpu` or `a2-megagpu` machine types instead of adding an accelerator.
For older GPUs including V100 and T4 you still specify an accelerator and the number of them to attach.
This PR ensured the cloud init is passed a correct `gpu_instance` regardless of the GPU selection method.
> Fix GPU flag for A100

- dask_cloudprovider/gcp/instances.py
Currently GCPCluster expects the `source_image` to be passed in the format `projects/<projectid>/global/images/<source_image>`.
This PR allows for just the `<source_image>` name, assuming it is in the same project as we are launching the cluster. We also handle the full image URI such as `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20201111a`.
> Allow multiple source image formats in GCPCluster

- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/gcp/tests/test_gcp.py
- dask_cloudprovider/generic/cloud-init.yaml.j2
Due to a typo and missing attribute bootstrapping is being skipped on GCP. 
This appears to have been missed because the default GCP Ubuntu image comes with Docker pre installed.
> Fix bootstrapping on GCP

- dask_cloudprovider/aws/ecs.py
* This change resolves the issue of the maximum number of open file descriptors/network connections being exceeded at runtime. This is documented  in the Dask Distributed FAQs (https://distributed.dask.org/en/latest/faq.html). The issue occurs on `FargateCluster` nodes under some types of heavy workloads with large numbers of workers.
* The `nofile` hard and soft ulimits are set to `65535` (from default `1024`) in both the scheduler and worker nodes via the ECS task  definitions for each.
* Also see https://github.com/dask/distributed/issues/1858
> Increase file descriptor limits on ECS/Fargate workers

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/aws/ecs.py
- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/azureml/azureml.py
- dask_cloudprovider/digitalocean/droplet.py
- dask_cloudprovider/gcp/instances.py
Updated import error messages to be consistent and reflect the current packaging state:
- All conda commands now have `-c conda-forge` argument.
- Simplified `python -m pip` command because it is mentioned in a comment already.
- AzureML and DigitalOcean packages are not currently on confa-forge and it's not our place to take on that maintenance. So simplified the error message to only mention pip.
- Google cloud conda error now says to install `dask-cloudprovider` instead of the specific dependencies (relies on  conda-forge/dask-cloudprovider-feedstock#9)
> Fix import error messages

- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/gcp/tests/test_gcp.py
Closes #179.
It looks like if you don't use a `googleapiclient` compute object for a while the tokens can expire.
This PR wraps the client in a class which will re-authenticate if an exception is raised.
> Wrap googleapiclient compute in class to refresh expired tokens

- ci/environment-3.7.yml
- ci/environment-3.8.yml
Pip seems to be failing to install Dask and Distributed from master in recent CI runs.
Attempting to install Dask from exactly the same URL as distributed does make dependency resolution easier.
> Install Dask from conda-forge before doing a dev install

- .github/workflows/release.yml
- README.rst
- doc/source/index.rst
- doc/source/releasing.rst
This PR adds a GitHub Actions workflow which will attempt to build a package distribution for dask-cloudprovider.
It will also upload that package to PyPI if run on a tagged branch in dask/dask-cloudprovider.
> Build distribution and publish to PyPI on tags

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/cloudprovider.yaml
- requirements_test.txt
This PR adds two new config/keyword argument options to `EC2Cluster`.
**key_name**
With `key_name` you can assign an existing key pair to all instances in your cluster. This is useful to enable debugging via SSH.
*Note that you will need to ensure you choose a security group which allows port 22*.
```console
$ aws ec2 describe-key-pairs  --query 'KeyPairs[*].KeyName' --output text
myawesomekey
```
```python
from dask_cloudprovider.aws import EC2Cluster
cluster = EC2Cluster(
key_name="myawesomekey",
security_groups=["sg-aabbcc112233"]  # Security group which allows ports 22, 8786, 8787 and all internal traffic
)
cluster.close()
```
**iam_instance_profile**
The `iam_instance_profile` enables you to assign an IAM Role to all instances created.
A common use case would be to create an EC2 role …
> Expose SSH key and Instance IAM Role config options in EC2Cluster

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/cloudprovider.yaml
There are situations where you may want to specify which availability zone to use. This PR adds a config option to enable this.
**Specify single AZ**
```python
cluster = EC2Cluster(region="us-east-1", availability_zone="us-east-1a")
```
**Specify multiple AZs**
Scheduler and worker VMs will be randomly assigned.
```python
cluster = EC2Cluster(region="us-east-1", availability_zone=["us-east-1a", "us-east-1b"])
```
> Add config option to specify availibility zone

- .github/workflows/release.yml
Pushing tags to forks will currently trigger a release, which will fail due to a missing secret.
This PR updates the if to avoid this.
> No publish forks

- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/azure/tests/test_azurevm.py
- dask_cloudprovider/digitalocean/droplet.py
- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/gcp/tests/test_gcp.py
- dask_cloudprovider/gcp/tests/test_utils.py
- dask_cloudprovider/gcp/utils.py
- dask_cloudprovider/generic/tests/test_vmcluster.py
- dask_cloudprovider/generic/vmcluster.py
The primary change here is adding the `VMCluster.call_async` method which takes an IO-bound blocking function and runs it in a thread. This allows us to await these functions and therefore run them concurrently.
The main benefit is that it resolves issues like #187 by allowing workers to be created concurrently.
The rest of the PR applies this method to blocking code in the DigitalOcean and Azure cluster managers. 
Fixes #187
> Async cluster creation

- dask_cloudprovider/aws/ec2.py
We cannot use the provided subnet_id provided to EC2Cluster at the moment because of a typo, this PR fixes it.
> Fix typo so we use subnet_id when provided, otherwise use config

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/aws/tests/test_ec2.py
- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/azure/tests/test_azurevm.py
- dask_cloudprovider/digitalocean/droplet.py
- dask_cloudprovider/digitalocean/tests/test_droplet.py
- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/gcp/tests/test_gcp.py
- dask_cloudprovider/generic/cloud-init.yaml.j2
- dask_cloudprovider/generic/vmcluster.py
Add an extra configuration option to specify extra docker arguments.
```python
from dask_cloudprovider.azure import AzureVMCluster
cluster = AzureVMCluster(docker_args="--privileged")
#
```
Closes #223
> Add extra docker args option

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/digitalocean/droplet.py
- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/gcp/tests/test_gcp.py
- dask_cloudprovider/generic/vmcluster.py
- doc/source/conf.py
- doc/source/index.rst
- doc/source/security.rst
This PR implements the `security` keyword argument for `VMCluster` based cluster managers.
This depends on dask/distributed#4364 as credentials are distributed via the Dask config and it seems there are a couple of bugs in the way this works.
Setting `security=True` will generate temporary credentials which will be distributed to the scheduler and workers at creation time. This is also the new default option.
```python
>>> from dask_cloudprovider.gcp import GCPCluster
>>> from dask.distributed import Client
>>> cluster = GCPCluster(n_workers=1, security=True)
>>> client = Client(cluster)
>>> client
<Client: 'tls://10.142.0.29:8786' processes=0 threads=0, memory=0 B>
```
Note the TLS here in the connection URL. Only clients with the credentials will be able to connect. In this example the …
> Implement security option in VM cluster managers

- dask_cloudprovider/generic/vmcluster.py
Looks like I broke a variable name when resolving a merge conflict.
Closes #247
> Fix broken protocol variable name

- dask_cloudprovider/gcp/instances.py
Here's a simple fix for #255.
As it stands, if preemptible instances are enabled, all instances in the cluster - including the scheduler - are preemptible. It would be better if the scheduler instance was always a standard (non-preemptible) instance. Suggestions for how to do that would be very welcome.
> Add option for preemptible instances on GCP

- dask_cloudprovider/aws/tests/test_ec2.py
- dask_cloudprovider/generic/cloud-init.yaml.j2
When an env_vars variable is passed to the docker run command and
it contains one or more space characters, we need to wrapp the
value in double quotes.
> Critical Fix for #257.

- dask_cloudprovider/azure/__init__.py
- dask_cloudprovider/azure/utils.py
- doc/source/azure.rst
- doc/source/conf.py
- requirements.txt
Azure spot instances may be preempted anytime which might lead to data
losses on the dask cluster. This commit adds a worker plugin that tries
to close worker gracefully before the VM is preempted. To do so, it
polls azure metadata service to listen to premption events
notifications.
fixes #239
> azure: add worker plugin for spot instances

- dask_cloudprovider/cloudprovider.yaml
- dask_cloudprovider/gcp/instances.py
fixes #252
With this PR you can optionally define the `on_host_maintenance` configuration with either `TERMINATE` or `MIGRATE`
> Add on_host_maintenance option in config

- dask_cloudprovider/aws/ecs.py
Only specify the `launchType` parameter if fargate True, and don’t default to EC2 otherwise. Otherwise, it is impossible to use a ECS cluster’s default capacity provider or specify a custom capacity provider via the `capacityProviderStrategy` property.
Closes #261.
> Only set launchType=FARGATE for ECS Fargate

- dask_cloudprovider/azure/azurevm.py
It turns out that the Azure API is case insensitive so it is possible to select an image size like `standard_nc6s_v3` instead of `Standard_NC6s_v3`.
Fixing the vm size check to be case insensitive and also look for `_` prefix to avoid `ND` matching in `standard`.
cc @manuelreyesgomez
> Fix case sensitivity in AzureVMCluster GPU instance checks

- dask_cloudprovider/cloudprovider.yaml
- dask_cloudprovider/gcp/instances.py
Exposed disk type as an option for `GCPCluster`.
Closes #272
> [GCP] Add disk type config option

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/digitalocean/droplet.py
- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/generic/vmcluster.py
Adds a debug flag to all `VMCluster` based cluster managers. This can then be used for printing more verbose output when starting clusters. For now, it prints the `cloud_init` file at render time.
> Add debug flag to VMCluster

- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/cloudprovider.yaml
Seems we are leaving the OS disk to the default size which in many cases is 30GB.
This PR bumps that default explicitly to 50GB and also makes it configurable.
Also making use of the new debug flag added in #271 to print out all VM parameters at creation time.
> Make disk size configurable

- dask_cloudprovider/aws/ecs.py
Thanks for this awesome library! I was spinning up a Fargate Cluster with a custom policy based on the roles in the documentation and ran into a few missing IAM roles. I've added the ones I had to add to the docstring.
Note that I only tested this on a cluster with no specified resources but I'm reasonably confident that they would be needed for a one where resources are specified too.
> Update documentation for required FargateCluster IAM Roles

- dask_cloudprovider/aws/ecs.py
I was tripping over a small documentation typo the other day when working with the ECS/Fargate provider and realised that there is a missing plural to one of the listed ec2 actions for the required IAM policies.
`ec2:DescribeSecurityGroups` is the correct name of the action, this is listed in the documentation [here](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html) and can also be verified in the IAM console where IAM will complain on not recognising `ec2:DescribeSecurityGroup` when editing a policy.
A very small documentation contribution, thanks for all the work with this!
> Correct ec2 action name in documentation

- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/cloudprovider.yaml
- setup.py
This PR :
- Adds support for using Marketplace VM images that has plans while creating AzureVM Cluster. 
- Closes [Issue#293](https://github.com/dask/dask-cloudprovider/issues/293) 
**More Details on Azure Marketplace VM issue**
Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request when using the python sdk or cli. This is applicable to the images which has plans. For example the pre-build *NVIDIA GPU-Optimized Image for AI & HPC* image made available by NVIDIA.
As an example, the input fields for creating a VM using *NVIDIA GPU-Optimized Image for AI & HPC* 21.02.2 can be found using the following: 
```bash
>> az vm image show --publisher nvidia --offer ngc_azure_17_11 --sku ngc-base-version-21-02-2 …
```
> Added support for using Marketplace VM images with plans in AzureVMCluster

- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/config.py
Make the `config` interfaces in `AzureVMCluster` consistently reference `AzureVMCluster.config` rather than sometimes referring out to `dask.config` itself. 
This also:
* enables nested config access via `.` notation, as per `dask.config.get`
* fixes a bug with accessing the `resource_group` key from `dask.config`.
Fixes #297 - see also the discussion there on the best approach for this fix.
> [Azure] Improve cluster config interface

- doc/source/troubleshooting.rst
Explaining "The requested CPU configuration is above your limit" AWS error and how to address it.
> Adding troubleshoot doc for CPU config above limit for ECS/Fargate (dask#299)

- dask_cloudprovider/aws/ecs.py
Fixes #309.
Related to #124.
@jacobtomlinson, I still need to try this out, but this is what I was thinking. `_update_task` seems to be the call that hits this error the most. It's used in 4 different places and only one of them is currently successfully backing off so I'm still getting this exception all over the place. Hopefully this will address the problem.
> Backing off within _update_task to avoid ThrottlingException

- dask_cloudprovider/aws/ecs.py
Runs Workers on `FARGATE_SPOT` and Scheduler on `FARGATE` capacity providers if `FargateCluster(fargate_spot=True)`
> [Dask] Add support for AWS Fargate Spot clusters

- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/azure/tests/test_azurevm.py
- dask_cloudprovider/digitalocean/droplet.py
- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/generic/cloud-init.yaml.j2
- dask_cloudprovider/generic/vmcluster.py
- dask_cloudprovider/hetzner/vserver.py
- doc/source/troubleshooting.rst
Allows users to specify additional bash commands to be run during the bootstrap before the Dask components are started.
One useful use case for this is logging into a private Docker registry before attempting to pull an image. Closes #318.
```python
from dask_cloudprovider.azure import AzureVMCluster
cluster = AzureVMCluster(...
docker_image="my_private_image:latest",
extra_bootstrap=["docker login -u 'username' -p 'password'"])
```
> Add extra bootstrap config to VM based clusters

- dask_cloudprovider/aws/tests/test_ec2.py
- dask_cloudprovider/azure/tests/test_azurevm.py
- dask_cloudprovider/conftest.py
- dask_cloudprovider/digitalocean/tests/test_droplet.py
- dask_cloudprovider/gcp/tests/test_gcp.py
- dask_cloudprovider/hetzner/tests/test_vserver.py
- doc/source/index.rst
- doc/source/testing.rst
Currently tests which require credentials will skip. However there are situations where you would prefer not to create external resources even if credentials are configured.
This PR makes all tests that create cloud resources opt-in with a `--create-external-resources` pytest flag.
Also added a doc page for testing.
> Add --create-external-resources pytest flag to opt into running end-to-end tests

- dask_cloudprovider/generic/vmcluster.py
This was already working for new VMs created using the scale() feature of SpecCluster, but this change allows subclasses of VMCluster to specify their own _new_worker_name, and its initial n_workers (created in _start()) will be named accordingly.
> VMCluster should name wokers based on SpecCluster new_worker_name()

- dask_cloudprovider/aws/ecs.py
On creation of an ECS cluster, an error is thrown if `~/.aws/config` does not exist. It will also only check for stale resources in the default region specified in `~/.aws/config`.
I've updated `_cleanup_stale_resources` to allow passing of kwargs to fix this. `ECSCluster(region_name="xxxx")` will now check for stale resources in the specified region before creation.
This PR should also fix issue #71.
> Pass appropriate kwargs to _cleanup_stale_resources for ECS

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .readthedocs.yml
- ci/environment-3.10.yml
- ci/environment-3.9.yml
- ci/scripts/test_imports.sh
- setup.py
Dask dropped Python 3.7 recently so just following up here with the same. Also added CI for 3.9 and 3.10.
> Drop python 37

- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/generic/vmcluster.py
It's possible to configure the scheduler port (using `scheduler_options={"port":"<custom>"}`) but it's not taken into account in GCP.
This commit gets the scheduler_port from `scheduler_options` and defines `SchedulerMixin.port` that is then reused by `GCPScheduler` and `GCPWorker` to define the scheduler address.
> gcp: configure scheduler port

- dask_cloudprovider/aws/ecs.py
ECS would not allow FARGATE_SPOT tasks to be created without FARGATE_SPOT being added as a capacityProvider to the cluster.
Also added FARGATE to support schedulers (on demand) and workers (spot) within the same cluster.
>  Fargate with spot instances fails with InvalidParameterException #328

- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/azure/tests/test_azurevm.py
Looks like the Docker image isn't being passed through correctly in `AzureVMCluster`.
Fixes #349
> Fix docker image passing through in AzureVMCluster

- dask_cloudprovider/aws/ecs.py
The `SchedulerAddress` object can be used as a proxy for the `Scheduler` object and therefore needs to be awaitable.
Fixes #346
> Make SchedulerAddress awaitable

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/cloudprovider.yaml
Some organizations (including mine) require resources to be tagged on creation.
This PR adds this feature. AWS supports tagging instances and volumes on launch (see [the docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html)).
I implemented this by adding two optional parameters to `EC2Cluster`: `instance_tags` and `volume_tags`. These are passed in as dictionaries and then formatted for AWS, similarly to how this is done for `ECSCluster` tags.
> Add support for EC2 tags on instance creation

- dask_cloudprovider/aws/ec2.py
This PR adds the ability to set up an EC2 cluster whose instances do not have public IP addresses, and the scheduler/workers communicate via private IP.
> Ability to use EC2 private IP address

- doc/requirements-docs.txt
- doc/source/conf.py
On Monday, June 6th, dask.org will go live with a new design (see https://github.com/dask/community/issues/220). This PR is in preparation for the theme update for `dask-sphinx-theme` and can be merged in *after* https://github.com/dask/dask-sphinx-theme/pull/67 on Monday.
cc @jacobtomlinson @jsignell
> Update docs theme for rebranding

- dask_cloudprovider/aws/ecs.py
This fixes #360 : `scale` function in distributed looks for a status attribute. When passing an existing scheduler to ECSCluster we assume it is already running, and so return this status.
I replicated the issue on my account, then applied the change and saw that `scale` worked ok.
It might be more appropriate to update distributed to not depend on both the scheduler object as passed, as well as on rpc communication. Since the rpc is required anyway, it could be used to get the scheduler status (`scheduler_comm.status`), reducing the need for two sources of truth, but increasing communication (though without the communication no answer is correct)
Also note that `scale_down` has more interesting requirements, and can't be made to work easily.
> add status when passing existing scheduler to ECS

- dask_cloudprovider/aws/ec2.py
1. Pulled out the postprocessing into configure_vm, and wrap in try/catch
2. Put create_tags in a timeout loop.
3. moved initialization of the backoff variable outside of the timeout loop for ip_address_key, else it seems pointless?
4. moved the sleep call to end of loop for ip_address_key - sleeping before attempt seems wrong?
5. changed the ip_address_key check to self.instance.get(ip_address_key) - simpler, more readable, and equivalent?
6. botocore.config.Config(retries = dict(max_attempts=10)) - without this we get errors, seems to be a fairly standard AWS problem.
> Destroy VM is creation fails to avoid leaking VMs

- dask_cloudprovider/aws/ecs.py
- dask_cloudprovider/aws/helper.py
- dask_cloudprovider/aws/tests/test_helper.py
- dask_cloudprovider/cloudprovider.yaml
This PR adds `fargate_use_private_ip` to `cloudprovider.yaml`, which allows us to set defaults using dask config without passing a value to the `FargateCluster` constructor explicitly.
While making this update, I noticed that there is a lot of duplicated logic in `ECSCluster._start()`, specifically with how class attributes are set/updated. I cleaned this up by creating a helper function. This helper function is implemented as a mixin, as it would be nice to also use it in `EC2Cluster`. However, the corresponding logic there is a bit different. Namely, arguments from the constructor are not saved to the instance, and the config update happens in the constructor (as opposed to `_start`). So I decided not to include that in this PR, but I would be happy to refactor to use this mixin if …
> ECSCluster attr cleanup

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/cloudprovider.yaml
As title. See [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-cloudwatch-new.html) for documentation on detailed vs. basic monitoring.
> Ability to enable detailed monitoring for EC2 instances

- dask_cloudprovider/aws/ec2.py
gp3 is cheaper and more performant than gp2
https://aws.amazon.com/blogs/storage/migrate-your-amazon-ebs-volumes-from-gp2-to-gp3-and-save-up-to-20-on-costs/
> use gp3 by default for AWS EBS storage

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/cloudprovider.yaml
`FargateCluster` supports different instance types for the scheduler and workers (via the `scheduler_mem`, `scheduler_cpu`, `worker_mem`, `worker_cpu` arguments), but `EC2Cluster` does not provide this flexibility. This PR changes this by introducing two new arguments to `EC2Cluster`: `scheduler_instance_type` and `worker_instance_type`. 
I believe this flexibility gives a better experience, and it also establishes consistency with `FargateCluster`. For these reasons I propose deprecating `instance_type` in favor of the new args above. This PR was written with this deprecation in mind, however I did not want to introduce a breaking change. Thus my solution is to raise a deprecation warning when users supply the `instance_type` argument, and in this case both the scheduler and workers …
> EC2Cluster support for different instance types on scheduler and workers

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/cloudprovider.yaml
This PR makes 2 updates with the goal of enabling more configuration to be done "behind the scenes" rather than supplied explicitly to the `EC2Cluster` constructor.
1. Fixes a bug (introduced in #353) where `EC2Cluster` constructor argument `use_private_ip` had incorrect default value, preventing intended behavior w.r.t loading from `cloudprovider.yaml` default. This argument was not actually in `cloudprovider.yaml` before, so this PR adds it as well.
2.  Uncomment  `ami`, `vpc`, `subnet_id` and `security_groups` from `cloudprovider.yaml` EC2 config. To test my change, I ran the following snippet and verified that the created cluster had the correct ami; was in the VPC, subnet, and security_groups specified in my config, and used private IP address.
```
import dask
from …
```
> Enable all EC2 config options in `cloudprovider.yaml`

- dask_cloudprovider/aws/ecs.py
- dask_cloudprovider/cli/ecs.py
- dask_cloudprovider/cloudprovider.yaml
Scheduler port is now provided via configuration, and the IP address from the ECS API.
Closes #313
> Do not Parse Logs to Find Scheduler Address

- dask_cloudprovider/aws/ecs.py
Aims to resolve #135.
This set of changes provides an option to provide task definitions to the `ECSCluster` rather than having the cluster create one on startup. This can help with the proliferation of task definition families on the AWS UI, and with providing various settings to the task definition that the cluster doesn't support directly.
> Option to Provide Task Definition ARNs to ECSCluster

- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/azure/tests/test_azurevm.py
- dask_cloudprovider/azure/utils.py
- dask_cloudprovider/cloudprovider.yaml
- doc/source/azure.rst
- setup.py
This removes the use of a deprecated method from azure-cli-core to get the default subscription ID. It also removes the dependency on azure-cli-core.
For the common case, where the user has the Azure CLI installed and configured, we can get the subscription ID by parsing its output.
This PR also enables users to configure the subscription ID either in code or through the Dask config system.
A few related documentation updates for good measure.
FYI, I'm running the azure tests now. I'll let you know when they pass.
Closes https://github.com/dask/dask-cloudprovider/issues/376
> Avoid deprecated method to get Azure subscription ID

- dask_cloudprovider/aws/ecs.py
- dask_cloudprovider/cli/ecs.py
Adds an option to specify that the scheduler is on TLS
Fixes #386
> ECS: Add Option to Specify TLS Scheduler

- dask_cloudprovider/aws/ec2.py
- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/digitalocean/droplet.py
- dask_cloudprovider/generic/vmcluster.py
- dask_cloudprovider/hetzner/vserver.py
Intended to address [#254](https://github.com/dask/dask-cloudprovider/issues/254)
**Overview**
Let the scheduler and dashboard be publicly adressable with the workers in a vnet. The workers will always connect to the scheduler using the private IP, regardless of whether the scheduler has a public IP or not.
- `self.address` is the private IP
- `self.external_address` is the public IP on the scheduler object if public_ingress=True
**Testing**
Confirmed that it works by creating a cluster with `public_ingress = True` and a vnet allowing traffic on ports 8786-8787 from IP of local laptop only. Without this fix, the workers try to communicate with the scheduler using the public IP.
> Ensure workers use private ip to connect to scheduler

- doc/source/index.rst
In https://github.com/dask/dask/pull/9912, the organization of links for deploying options in [Deploy Dask Clusters](https://docs.dask.org/en/stable/deploying.html) was improved and we discussed linking to this central page in other projects.
cc @jacobtomlinson @gjoseph92
> Link to central deploying Dask page

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- .readthedocs.yml
- ci/environment-3.11.yml
- dask_cloudprovider/azure/tests/test_azurevm.py
- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/gcp/tests/test_gcp.py
- versioneer.py
This fixes pre-commit failure https://github.com/dask/dask-cloudprovider/actions/runs/6709474379/job/18232600682
It looks like the default python version in the action was bumped to the latest 3.12. **flake8** in version `3.9.2` does not work with python3.12.
I've bumped the **flake8** and **black** to the latest versions. The new **black** formatter removed a few empty lines.
I've also added a support for python 3.11 and preliminary support for 3.12. Before supporting 3.12 we have to wait for a new aiohttp version https://github.com/aio-libs/aiohttp/issues/7675
> Bump flake8 and black in pre-commit config and add support for 3.11

- dask_cloudprovider/aws/ecs.py
- dask_cloudprovider/cloudprovider.yaml
Support explicit runtime platform architecture selection for ECS and Fargate clusters
> ARM64 support for ECS and Fargate

- dask_cloudprovider/aws/ecs.py
When kwargs is typed as `kwargs: dict`, this is interpreted as Dict[str, dict].
See https://peps.python.org/pep-0484/#arbitrary-argument-lists-and-default-argument-values
This issue led to unexpected warnings in Pycharm. I did not check if this issue is present in other parts of the code
> Fix incorrectly documentet kwargs in AWS ECS

- doc/source/troubleshooting.rst
Without additional steps GCPCluster cannot use images from Artifact Registries in the same project. Add example of how to set up access.
> Add example of authenticating Docker in VMs to use GCP Artifact Registry

- .github/workflows/ci.yml
- .github/workflows/release.yml
- ci/environment-3.12.yml
- ci/scripts/test_imports.sh
- dask_cloudprovider/ibm/code_engine.py
- dask_cloudprovider/tests/test_imports.py
- doc/requirements-docs.txt
- setup.py
Bump up supported Python versions and resolve other CI issues.
> Remove Python 3.9 and add Python 3.12

- dask_cloudprovider/cloudprovider.yaml
- dask_cloudprovider/ibm/code_engine.py
All tested and working as expected!
> [IBM Code Engine] Added local disk variable for scheduler and worker

- dask_cloudprovider/aws/ecs.py
Using `FargateCluster` tonight, I found myself wanting to create a cluster using arm64 servers, because I was working with container images that were only built from arm64.
Thankfully, as of #425, that's now configurable easily via the `cpu_architecture` argument 🎉 
... but I didn't know what the valid values were for that. `arm64`? `aarch64`? does capitalization matter?
This proposes adding a link to the relevant AWS docs to help answer that question.
Tested `cpu_architecture="ARM64"` tonight and it worked great 😁 
ref: https://github.com/jameslamb/lightgbm-dask-testing/pull/68
> [aws] add docs on cpu_architecture for ECSCluster

- dask_cloudprovider/cloudprovider.yaml
- dask_cloudprovider/nebius/__init__.py
- dask_cloudprovider/nebius/instances.py
- dask_cloudprovider/nebius/tests/test_nebius.py
- doc/source/index.rst
- doc/source/installation.rst
- doc/source/nebius.rst
- setup.py
Add [Nebius AI Cloud](https://nebius.com) support
> Add Nebius AI Cloud support

- setup.py
Replaced Git-based dependency for Nebius with a versioned package (`nebius>=0.2.0`) for better stability and compatibility. This ensures easier management of dependencies and aligns with standard versioning practices.
> Update Nebius dependency to versioned release

- dask_cloudprovider/azure/azurevm.py
- dask_cloudprovider/digitalocean/droplet.py
- dask_cloudprovider/gcp/instances.py
- dask_cloudprovider/generic/vmcluster.py
- dask_cloudprovider/hetzner/vserver.py
- dask_cloudprovider/openstack/instances.py
Currently the implementations of `VMInterface` call `self.cluster.call_async()` when they want to run a synchronous function. This reference to the parent cluster instance means that `VMInterface` instances can't exist outside of a cluster.
This PR adds a `VMInterface.call_async` method which encapsulates the call to `self.cluster.call_async()`. This allows others to override this method if they wish more easily.
> Remove calls to `self.cluster.call_async()`

- dask_cloudprovider/generic/vmcluster.py
This call should be to the `call_async` method on the prarent cluster.
Closes #460
> Fix VMInterface call_async recurive typo

- dask_cloudprovider/gcp/instances.py
While working on the issue 390 in [this PR](https://github.com/dask/dask-cloudprovider/pull/451), it appears I have made a mistake with the logging "No GPU instances configured" message. The GCPCluster does not have any loggers, so it is better to just make a print statement.
> Fixing the log error

- dask_cloudprovider/generic/vmcluster.py
- dask_cloudprovider/utils/config_helper.py
- dask_cloudprovider/utils/tests/test_config_helper.py
Hi, this solves the issue (https://github.com/dask/dask-cloudprovider/issues/249). Thanks.
> Add pruning default dask configs before serialization

- dask_cloudprovider/aws/ecs.py
- dask_cloudprovider/aws/helper.py
Introduce a tags parameter to the `create_default_security_group` function, allowing the specification of tags when creating a default security group. This enables the `_cleanup_stale_resources` to capture those security groups which would otherwise be left untouched in the cleanup process.
> Add tags parameter to create_default_security_group function

- dask_cloudprovider/cloudprovider.yaml
- dask_cloudprovider/gcp/instances.py
- Adds the ability to specify authentication oauth2 scopes for an instance in google compute engine
- This allows for workers/schedulers to use their credentials to access other services e.g. artifact registry or secret manager for any work
> Allow for the specification of auth scopes for google compute engine instances
