README.rst
dask_cloudprovider/cloudprovider.yaml
setup.py

Removed alpha warning and updated links to dask org

Migration docs

---

dask_cloudprovider/cli/ecs.py
dask_cloudprovider/cloudprovider.yaml
dask_cloudprovider/providers/aws/ecs.py
dask_cloudprovider/utils/logs.py

All code `TODO`s have been migrated to GitHub issues.

Remove todos

---

dask_cloudprovider/cloudprovider.yaml
doc/source/index.rst

Already removed from README but forgot to remove from the docs too.

Remove docs alpha warning

---

dask_cloudprovider/cloudprovider.yaml
dask_cloudprovider/providers/aws/ecs.py

Simplify code by moving all default values into the config file.
Closes #3

Move all default values into config file

---

dask_cloudprovider/providers/aws/ecs.py

This PR adds `aws_access_key_id`, `aws_secret_access_key`, and `region_name` keyword arguments to `ECSCluster.__init__` which are then used to override defaults when creating `botocore` service clients.
Closes #30

Adds boto client options

---

dask_cloudprovider/providers/aws/ecs.py

Fix nthreads in situations where cpu is less than 1

---

doc/source/index.rst

Add more detail to the GPU section to describe what happens as a result of setting the `worker_gpu` kwarg.

Improve GPU documentation

---

doc/source/index.rst

Added some information to help users get a working custom docker image for FargateCluster

Added custom container info to docs

---

dask_cloudprovider/providers/aws/ecs.py

In particular we need to use aiobotocore clients in an async context
manager.  So now rather than store these we recreate them each time.
This adds a modest cost increase of about 5ms on my machine, but also
simplifies cleanup a bit.
I believe that this change is also backwards compatibile
Fixes #80
Fixes #78
cc @quasiben @jacobtomlinson @rsignell-usgs @Norticaranda

Support aiobotocore version 1.0

---

dask_cloudprovider/providers/aws/ecs.py

ECS Platform version 1.4.0 added [support for volume mounts](https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/). This PR allows either type of ECS cluster (Fargate or EC2) to specify mount points and volumes for the Dask worker tasks and, optionally, for the Dask scheduler task.
This has been tested successfully with an EFS volume and Dask cluster on Fargate. (Dask workers were able to successfully access files on a mounted EFS drive at the provided path mount point.)

Allow mount points and volumes for Fargate & ECS Clusters

---

dask_cloudprovider/providers/aws/ecs.py

keep fetching until nextToken is empty
fixes https://github.com/dask/dask-cloudprovider/issues/111

basic cycling through paging for aws api

---

doc/source/index.rst

fix Python code for Azure ML cluster creation not showing 

---

.circleci/config.yml
dask_cloudprovider/providers/aws/tests/test_ecs.py
dask_cloudprovider/providers/azure/azureml.py
dask_cloudprovider/providers/azure/setup/start_scheduler.py
dask_cloudprovider/providers/azure/tests/test_azureml_gpu.py

Closes #118 
- Fix `flake8` command in CI
- Fix PEP8 issues
- Run `black`

Fix flake8

---

dask_cloudprovider/__init__.py
dask_cloudprovider/providers/aws/ecs.py
dask_cloudprovider/providers/azure/azureml.py
doc/source/index.rst
requirements.txt
setup.py

Hi there, I've raised this PR to attempt to improve the developer experience for people only interested in one cloud provider!

Extract provider specific requirements into extras_require in setup.py

---

.gitignore

Thanks for this great project! I've just started getting familiar with it, and wanted to contribute back.This PR proposes adding a few more extensions for object created from C/C++ code, and some for SSH key material.
Thanks for your time and consideration.

add more object file extensions to .gitignore

---

doc/source/index.rst

update and extend azureml docs

---

dask_cloudprovider/gcp/instances.py

The change in #162 was not consistent with other attributes. Changing property to attribute to be consistent.

Make GCPCluster consistent

---

requirements.txt

Update requirements for distributed

---

doc/source/installation.rst

Fix extras require name for Google Cloud

---

.github/workflows/ci.yml
dask_cloudprovider/cloudprovider.yaml
dask_cloudprovider/gcp/instances.py

Resolves https://github.com/dask/dask-cloudprovider/issues/161
cc @eric-czech

Configure scheduler internal/external ip with public_ingress option

---

setup.py

Change README filename to rst and update Python version

---

setup.py

Set dependency minimum versions to versions that were developed against.
Closes #184

Set minimum dependency versions

---

dask_cloudprovider/azure/azurevm.py
dask_cloudprovider/azure/tests/test_azurevm.py
dask_cloudprovider/cloudprovider.yaml

There was some confusing raised in #188 due to the way we set a default location.
This PR removes the default location and adds a check to make this parameter mandatory.

Remove default location

---

dask_cloudprovider/azure/azurevm.py
dask_cloudprovider/cloudprovider.yaml

Closes #193.
@lostmygithubaccount would you mind testing this?

Allow choosing a different VM size for the scheduler

---

dask_cloudprovider/gcp/instances.py

Fixes https://github.com/dask/dask-cloudprovider/issues/225

Add monitoring.write scope for GCP #225

---

dask_cloudprovider/gcp/instances.py
dask_cloudprovider/gcp/tests/test_utils.py
dask_cloudprovider/gcp/utils.py
dask_cloudprovider/generic/vmcluster.py

Use internal IP whilst in GCE

---

README.rst

Added PyPI and Conda Forge badges to the README

Package repo badges

---

dask_cloudprovider/aws/ecs.py

Add missing perms for IAM role

---

doc/requirements-docs.txt
doc/source/conf.py

Bumping the minimum docs theme to use the new version. This isn't strictly necessary but I wanted to raise a PR to trigger the rtd preview and check everything looks ok.
xref dask/dask-sphinx-theme#54

New docs theme

---

dask_cloudprovider/aws/ecs.py

The currently supported workflow is to start an ECSCluster before doing any dask work, and only once it's started start doing work.
Recently I have moved to the following workflow: start a dask LocalCluster, start working, and if I decide I need more computing power then I spin up an ECSCluster that connects to the existing Scheduler. I do this from a separate python process, maybe even a different machine, and I watch the number of workers grow and the tasks finish in the dashboard. This also decouples the computing resources from the code actually using dask.
Making the cluster use an existing scheduler is easy enough, just set the `scheduler` member to something that has the correct `address` attribute.
Allowing for multiple clusters to spin up and connect to the same cluster, for …

Add arguments so ECSCluster supports an existing scheduler

---

dask_cloudprovider/aws/ecs.py

The default number of threads in worker tasks is the number of vCPUs.
This pull request adds an argument `worker_nthreads` so that users can override the default. This is issue #320 .

New argument `worker_nthreads` in ECSCluster

---

dask_cloudprovider/azure/azurevm.py
requirements.txt
setup.py

I came to the problem that get_azure_cli_credentials does not return any credentials after a succesfull `az login` command. This fixed the issue

Support for current version of az-* libraries

---

setup.py

In #315 it was reported that newer versions of the Azure dependencies are causing problems. This PR adds an upper bound to those dependencies.
@jakirkham if you have some time would you mind checking I've done this right and let me know what I would need to do in the conda-forge recipe if anything?

Pin azure deps

---

dask_cloudprovider/aws/ecs.py

Fix typos in ECSCluster docstring

---

doc/requirements-docs.txt

See https://github.com/dask/dask-sphinx-theme/pull/84
cc @jacobtomlinson @emily-d-anderson

update dask-sphinx-theme for GA-4

---

dask_cloudprovider/openstack/instances.py

Hey all 👋
I noticed that the floating IP assignment logic I initially implemented was faulty (since it was using an older API endpoint). I fixed the implementation, and it works as expected with floating IPs.
Cheers!

[Openstack cloud provider] Fixed the floating ip logic
